NativeScript/nativescript-angular

- ng-sample/app/benchmark.ts
- ng-sample/app/renderer-test.ts
- ng-sample/package.json
- ng-sample/tsconfig.json
- package.json
- src/nativescript-angular/application.d.ts
- src/nativescript-angular/application.ts
- src/nativescript-angular/dom_adapter.ts
- src/nativescript-angular/renderer.ts
- src/nativescript-angular/zone.ts
> Angular2 Beta support

- src/nativescript-angular/directives/ns-directives.ts
Added TextValueAccessor directive to default NS_Directives.
> Included TextValueAccessor directive as NS_Directive.

- .gitignore
- ng-sample/package.json
- package.json
- src/global.d.ts
- src/nativescript-angular/application.ts
- src/nativescript-angular/directives/list-view.ts
- src/nativescript-angular/router/page-router-outlet.ts
- tests/app/global.d.ts
- tests/package.json
- tests/typings/chai.d.ts
Notable changes:
- Reintroducing global.d.ts/compat.d.ts in client projects. This time for an `Iterator` interface declaration to fix rxjs compiler errors.
- Ugly hacks around zone.js@0.5.15 that seem to work... for now.
> Upgrade to beta 7

- package.json
- src/nativescript-angular/application.ts
- tests/app/tests/bootstrap.ts
- tests/karma.conf.js
- tests/package.json
The previous zone.js@0.5.15 hack didn't work with the karma runner causing it to hang. This one seems to take care of the problem. Until 0.5.16. :angry:
> zone tests fix

- .travis.yml
- ng-sample/package.json
- src/nativescript-angular/application.ts
- src/nativescript-angular/platform-providers.ts
- src/nativescript-angular/renderer.ts
- tests/app/tests/bootstrap.ts
- tests/app/tests/mocha-config.ts
- tests/app/tests/renderer-tests.ts
- tests/app/tests/test-config.ts
- tests/hooks/after-prepare/nativescript-unit-test-runner.js
- tests/package.json
- Fix the Karma runner issues
- Fix the Travis build
- Add a couple of E2E renderer tests using a fully bootstrapped app.
- Support bootstrapping an app at a non-root location.
> Karma testing and more

- src/nativescript-angular/view-util.ts
- tests/app/tests/bootstrap.ts
- tests/app/tests/property-sets.ts
- tests/app/tests/renderer-tests.ts
Takes care of NativeScript/NativeScript#1735
> Fix conversion for number/boolean property values.

- ng-sample/app/app.ts
- ng-sample/app/examples/action-bar/action-bar-test.ts
- ng-sample/app/examples/modal/modal-content.ts
- ng-sample/app/examples/modal/modal-test.ts
- ng-sample/app/examples/navigation/nav-component.ts
- ng-sample/package.json
- package.json
- src/nativescript-angular/common/detached-loader.ts
- src/nativescript-angular/directives/dialogs.ts
- src/nativescript-angular/modal-dialog.d.ts
- src/nativescript-angular/modal-dialog.ts
- src/nativescript-angular/router/page-router-outlet.ts
- src/nativescript-angular/services/dialogs.ts
- src/nativescript-angular/view-util.ts
- tests/app/tests/modal-dialog.ts
- tests/app/tests/renderer-tests.ts
- tests/app/tests/router.ts
- tests/app/tests/test-app.ts
- tests/package.json
> Modal dialog service

- src/nativescript-angular/element-registry.ts
Just added FormattedString and Span to element registration file. FormattedString and Span should be used with the short-hand syntax.
```XML
<Label>
<FormattedString>
<Span text="Some text" fontAttributes="Bold" ></Span>
</FormattedString>
</Label>
```
> Added FormattedString and Span to elements registry.

- src/nativescript-angular/directives/list-view-comp.ts
`$implicit` is set within `setupViewRef`method to `data.item` due to some copy/paste error.
> Fixed `$implicit` property setting.

- src/nativescript-angular/renderer.ts
Solves the problem of attaching a node and immediately moving it to another
location in the visual tree without Angular noticing. That breaks the next
attach as it will attach nodes to the new location instead of the original
one.
Originally reported for RadSideDrawer running on iOS.
//cc @vakrilov, @sophialazarova
> Attaching a node to a parent remembering templateParent.

- .ctags-exclude
- ng-sample/app/app.ts
- ng-sample/app/examples/renderer-test.html
- ng-sample/package.json
- package.json
- src/nativescript-angular/view-util.ts
- tests/app/tests/style-properties.ts
- tests/package.json
Support style bindings:
- `[ngStyle]="{'background-color': 'red'}"`
- `[style.backgroundColor]="'red'"`
Fixes #229. Merge after NativeScript/NativeScript#2120 lands on master.
> Implement Renderer.setElementStyle.

- src/nativescript-angular/common/detached-loader.ts
- src/nativescript-angular/directives/dialogs.ts
- src/nativescript-angular/router/page-router-outlet.ts
> Remove usages of Dynmamic ComponentLoader

- ng-sample/app/examples/navigation/router-outlet-test.ts
- src/nativescript-angular/renderer.ts
Emit loaded event just after attaching to it, but element is already loaded (due to some timings within an angular project).
> Emit loaded event after attaching to.

- nativescript-angular/common/detached-loader.ts
- tests/app/tests/detached-loader-tests.ts
Resolves #273 
@NathanWalker - this should fix the similar problem in the project [ShoutOutPlay](https://github.com/NathanWalker/ShoutOutPlay)
> Detached loader change detection

- nativescript-angular/directives/list-view-comp.ts
- ng-sample/app/examples/list/list-test.ts
When custom template is used in angular ListView, a ProxyViewContainer, from custom template, is silently wrapped in a StackLayout which results in an incorrect view to store related angular EmbeddedView reference.
> Fixed problem with ListView in ios when CustomTemplate is used.

- nativescript-angular/application.ts
- nativescript-angular/polyfills/console.ts
- nativescript-angular/router/ns-location-strategy.ts
- nativescript-angular/router/ns-router-link.ts
In this PR:
- Polyfill for `console.group()` - needed to support `enableTracing: true` router option in android
- FIX: Navigating to same url triggers navigation to previous page.
> Router fixes

- nativescript-angular/application.ts
- nativescript-angular/hooks/before-livesync.js
- ng-sample/app/app.ts
- ng-sample/app/examples/livesync-test/first/first.component.css
- ng-sample/app/examples/livesync-test/first/first.component.ts
- ng-sample/app/examples/livesync-test/first/first.component.xml
- ng-sample/app/examples/livesync-test/livesync-test-app.ts
- ng-sample/app/examples/livesync-test/second/second.component.css
- ng-sample/app/examples/livesync-test/second/second.component.ts
- ng-sample/app/examples/livesync-test/second/second.component.xml
In this PR: 
- Reboot the application when fast-livesyncing (when xml/html/css file is changed)
- Exposed `onBeforeLivesync` and `onAfterLivesync` events in `nativescript-angular/application` that can be used to plug in additional logic on when livesync-ing. For example store router url and then navigate to the same page.
> Fast livesync

- nativescript-angular/application.ts
- nativescript-angular/http.ts
- nativescript-angular/http/ns-http.ts
- ng-sample/app/app.ts
- ng-sample/app/examples/http/http-test.ts
- ng-sample/package.json
This can now be imported from anywhere and used in either `nativeScriptBootstrap` providers array or `Component` `providers` array:
```
import {NS_HTTP_PROVIDERS} from 'nativescript-angular/http';
```
I have also added a Guide to the Wiki regarding `Http`:
https://github.com/NativeScript/nativescript-angular/wiki/Http
closes https://github.com/NativeScript/nativescript-angular/issues/305
> fix(Http): export NS_HTTP_PROVIDERS to be used anywhere

- ng-sample/app/app.ts
- tests/app/main.ts
The `nativescript-angular/application` should aways come first.
Spotted in #326
> Reorder imports in ng-sample

- nativescript-angular/renderer.ts
- tests/app/tests/renderer-tests.ts
- tests/app/tests/style-properties.ts
- tests/app/tests/test-app.ts
- tests/package.json
> FIX: All events should execute inside zone

- .travis.yml
- build/travis-scripts/add-publishConfig.js
Added date and travis build number to version to create unique version for @next builds.
> Added date and travis build number to version to create unique version

- nativescript-angular/element-registry.ts
- nativescript-angular/view-util.ts
- tests/app/tests/property-sets.ts
As of NativeScript/NativeScript#2465 there is a `cssClasses` field in the view.
We need to rename the one we use in the `ViewExtensions`
cc @PanayotCankov
> cssClasses renamed to ngCssClasses

- nativescript-angular/application.ts
- nativescript-angular/platform-providers.ts
- nativescript-angular/router-deprecated/page-router-outlet.ts
- nativescript-angular/router/ns-location-strategy.ts
- nativescript-angular/router/ns-platform-location.ts
- nativescript-angular/router/ns-router-link.ts
- nativescript-angular/router/ns-router.ts
- nativescript-angular/router/page-router-outlet.ts
- nativescript-angular/router/router-extensions.ts
- ng-sample/app/app.ts
- ng-sample/app/examples/router/clear-history-test.ts
- ng-sample/app/examples/router/clear-history.component.html
- ng-sample/app/examples/router/login-test.ts
- ng-sample/app/examples/router/styles.css
- tests/app/tests/ns-location-strategy.ts
- tests/app/tests/snippets.ts
Added a way to:
-  Clear page navigation history
- Specify page transition on navigation.
Resolves #218
Resolves #284
> ClearHistory and PageTransitions 

- nativescript-angular/view-util.ts
- tests/app/tests/platform-filter-components.ts
- tests/app/tests/property-sets.ts
> Fixed platform specific attribute setting

- nativescript-angular/router/ns-router-link-active.ts
- nativescript-angular/router/ns-router-link.ts
- nativescript-angular/router/ns-router.ts
The directive works exactly as the angular default one.
Didn't create tests yet but if needed I can look into it maybe. To test it yourself you can just add the directive to some routing links and verify that the class is added (also works on ancestor):
```xml
<StackLayout horizzontalAlign="left">
<Label text="Home" [nsRouterLinkActive]="['selected']" [nsRouterLink]="['/home']"></Label>
<Label text="Test" [nsRouterLinkActive]="['selected']" [nsRouterLink]="['/test']"></Label>
</StackLayout>
```
> Implemented nsRouterLinkActive directive (angular2 routerLinkActive)

- nativescript-angular/http/ns-http.ts
> NSHttp.get return type fixed

- nativescript-angular/router/ns-location-strategy.ts
- nativescript-angular/router/router-extensions.ts
- tests/app/tests/ns-location-strategy.ts
Add a `canGoBack()` method to `RouterExtensions`
Related to #477
> RouterExtensions.canGoBack() method added

- nativescript-angular/directives/dialogs.ts
- nativescript-angular/platform.ts
- ng-sample/app/examples/modal/modal-test.ts
- tests/app/tests/modal-dialog.ts
`ModalDialogHost` is deprecated. You can now call `ModalDialogService.showModal()` and pass a `ViewContainerRef` in the options instead (you will have to inject the `ViewContainerRef`). 
This approach is similar to [angular-material2 dialog](https://github.com/angular/material2/blob/0e0ff0e7aae4a4f87ad92e17bc1af14e20a3e17a/src/demo-app/dialog/dialog-demo.ts#L14-L29).
Related to #460 and #430
> Modal dialogs reafactoring

- nativescript-angular/directives/dialogs.ts
- nativescript-angular/platform-providers.ts
- nativescript-angular/platform.ts
- nativescript-angular/router/page-router-outlet.ts
- ng-sample/app/app.ts
- ng-sample/package.json
Add support for providing custom PageFactory. The factory is used when creating pages when:
- Bootstraping/livsyncing the application.
- Doing page navigation (with `<page-router-outlet`).
- When showing custom modal dialogs.
Resolves #394 
cc @VladimirAmiorkov
> Support for custom page factory providers

- nativescript-angular/value-accessors/selectedIndex-value-accessor.ts
The TabView CSS selector was wrong and broke directive registration.
Fixes #551
> Fix TabView value accessor selector.

- tests/app/tests/ns-location-strategy.ts
> Fix tests tsc errors

- nativescript-angular/platform-common.ts
> Respect AppOptions cssFile property

- nativescript-angular/directives/action-bar.ts
- nativescript-angular/element-registry.ts
- nativescript-angular/view-util.ts
- ng-sample/app/app.ts
- ng-sample/hooks/before-livesync/nativescript-angular-sync .js
- tests/app/tests/renderer-tests.ts
With angular `2.2.1` additional template anchors are created for components, which cause problems when added to content-view(ex. Page)
> FIX: Adding template anchors to ContentView

- nativescript-angular/directives/dialogs.ts
- nativescript-angular/nativescript.module.ts
- nativescript-angular/platform-common.ts
- nativescript-angular/view-util.ts
- tests/app/tests/modal-dialog.ts
`ModalDialogHost` will now throw when used
> deprecate modal-dialog-host

- nativescript-angular/common/detached-loader.ts
- nativescript-angular/common/utils.ts
- nativescript-angular/directives/action-bar.ts
- nativescript-angular/directives/dialogs.ts
- nativescript-angular/directives/list-view-comp.ts
- nativescript-angular/directives/platform-filters.ts
- nativescript-angular/directives/tab-view.ts
- nativescript-angular/file-system/ns-file-system.ts
- nativescript-angular/http/ns-http.ts
- nativescript-angular/package.json
- nativescript-angular/private_import_core.ts
- nativescript-angular/private_import_platform-browser.ts
- nativescript-angular/renderer.ts
- nativescript-angular/resource-loader.ts
- nativescript-angular/router/ns-platform-location.ts
- nativescript-angular/router/ns-router-link-active.ts
- nativescript-angular/router/ns-router-link.ts
- nativescript-angular/router/page-router-outlet.ts
- nativescript-angular/router/router-extensions.ts
- nativescript-angular/trace.ts
- nativescript-angular/tslint.json
- nativescript-angular/value-accessors/base-value-accessor.ts
- nativescript-angular/value-accessors/checked-value-accessor.ts
- nativescript-angular/value-accessors/date-value-accessor.ts
- nativescript-angular/value-accessors/number-value-accessor.ts
- nativescript-angular/value-accessors/selectedIndex-value-accessor.ts
- nativescript-angular/value-accessors/text-value-accessor.ts
- nativescript-angular/value-accessors/time-value-accessor.ts
> Chore(lint): add codelyzer

- nativescript-angular/common/detached-loader.ts
- nativescript-angular/directives/dialogs.ts
Host component bindings are not being updated otherwise.
Messy changelog due to fixing DOS line endings...
> fix(dialogs): Trigger change detection on dialog close.

- nativescript-angular/nativescript.module.ts
- nativescript-angular/platform-common.ts
- nativescript-angular/router.ts
- nativescript-angular/router/ns-module-factory-loader.ts
- tests/app/lazy-load-main.ts
- tests/app/main.ts
Register `NsModuleFactoryLoader` when using the Router.
cc: @sis0k0
> Add ns-module-factory-loader

- nativescript-angular/index.ts
- nativescript-angular/package.json
- nativescript-angular/value-accessors/base-value-accessor.ts
- nativescript-angular/value-accessors/checked-value-accessor.ts
- nativescript-angular/value-accessors/date-value-accessor.ts
- nativescript-angular/value-accessors/number-value-accessor.ts
- nativescript-angular/value-accessors/selectedIndex-value-accessor.ts
- nativescript-angular/value-accessors/text-value-accessor.ts
- nativescript-angular/value-accessors/time-value-accessor.ts
- ng-sample/package.json
- tests/app/tests/value-accessor-tests.ts
- tests/package.json
Just adding selectors for Control[formControlName] thanks to @clarenceh's excellent work in #526.
> Reactive forms support

- nativescript-angular/directives/list-view-comp.ts
Fixes bug when ListView component starts using wrong template if there is a nested <template> inside its item-template.
Added a sample repro of the problem in the [test-app-ng](https://github.com/NativeScript/tests-app-ng/commit/603c30b94850610311ed9c7612115aa77ec739a5)
To reproduce:
1. Navigate to listViewExamples -> nestedTemplate
2. ListView is shown as expected.
3. Click navigate, then go back.
4. ListView items should be the same again.
Resolves #572
cc @SvetoslavTsenov
> ListView using wrong template after navigation

- nativescript-angular/router.ts
- tests/app/first.component.ts
- tests/app/second.component.ts
- tests/e2e-tests/lazy-load-routing.js
Fix the navigation using extras like `clearHistory` to a lazy loaded module. Providers, especially `NSLocationStrategy` were instantiated multiple times.
> Fix navigate with clearHistory to a lazy loaded module

- nativescript-angular/router/ns-module-factory-loader.ts
Since `ns-module-factory-loader` contains [dynamic require call](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/router/ns-module-factory-loader.ts#L45), when it is webpacked, a [context module](https://webpack.github.io/docs/context.html#context-module) is generated for it. By default, when a module is dynamically required by a context module it must reside in the same directory as the context module in order to be resolved by the `webpack`'s require. This means that after [this change in the sdk examples](https://github.com/NativeScript/nativescript-sdk-examples-ng/commit/7feec82f8192b0de5704561686a535db90fb6598), the example app will crash with `Module not found` when a module that is not in the same directory as `ns-module-factory-loader.ts` is …
> Call the runtime require function instead of the webpack's one in ns-module-factory-loader

- nativescript-angular/directives/action-bar.ts
tns-core-modules@3.0.0 turned action items into views and they
can get removed as a part of the view detach process -- think
*ngIf templates.
The file contained a bunch of DOS line endings, so I fixed it too. The actual change is in the ActionItem ngOnDestroy implementation:
```TypeScript
public onActionDestroy(item: ActionItemDirective) {
if (item.element.nativeElement.actionBar) {
this.page.actionBar.actionItems.removeItem(item.element.nativeElement);
}
}
```
> fix(action-bar): Don't remove action items twice.

- nativescript-angular/animation-driver.ts
- nativescript-angular/animation-player.ts
- nativescript-angular/common/detached-loader.ts
- nativescript-angular/directives/action-bar.ts
- nativescript-angular/directives/dialogs.ts
- nativescript-angular/directives/list-view-comp.ts
- nativescript-angular/directives/platform-filters.ts
- nativescript-angular/directives/tab-view.ts
- nativescript-angular/element-registry.ts
- nativescript-angular/file-system/ns-file-system.ts
- nativescript-angular/platform-common.ts
- nativescript-angular/platform-providers.ts
- nativescript-angular/renderer.ts
- nativescript-angular/resource-loader.ts
- nativescript-angular/router.ts
- nativescript-angular/router/ns-location-strategy.ts
- nativescript-angular/router/ns-module-factory-loader.ts
- nativescript-angular/router/ns-router-link.ts
- nativescript-angular/router/page-router-outlet.ts
- nativescript-angular/router/router-extensions.ts
- nativescript-angular/trace.ts
- nativescript-angular/tsconfig.json
- nativescript-angular/value-accessors/checked-value-accessor.ts
- nativescript-angular/value-accessors/date-value-accessor.ts
- nativescript-angular/value-accessors/number-value-accessor.ts
- nativescript-angular/value-accessors/selectedIndex-value-accessor.ts
- nativescript-angular/value-accessors/text-value-accessor.ts
- nativescript-angular/value-accessors/time-value-accessor.ts
- nativescript-angular/view-util.ts
Needed for AoT support when using TypeScript 2.2.
Merge after NativeScript/NativeScript#3773.
> chore(modules): Use fully-qualified imports for tns-core-modules

- .gitignore
Hi!
This PR adds more files and folders to exclude in the `gitignore`.
Mostly Webstorm like and Visual Code editors.
There is not issue about that but I can create one and link it if you need me to.
If not added, tell us why? No need to add tests as i didn't change the code.
Thanks!
> fix(gitignore): Add editor files and folders to be excluded

- nativescript-angular/platform.ts
- tests/app/lazy-loaded.module.ts
- tests/app/main.ts
- tests/app/snippets/navigation/page-outlet.ts
- tests/app/tests/test-app.ts
Importing NativeScriptModule from "nativescript-angular/platform" leads to
including @angular/compiler in the bundle when doing AoT compilation
with webpack. Import from "nativescript-angular/nativescript.module"
should be used instead.
BREAKING CHANGE: User applications cannot import NativeScriptModule from
"nativescript-angular/platform" anymore.
Migration:
Before:
```
import { NativeScriptModule } from "nativescript-angular/platform";
```
After
```
import { NativeScriptModule } from
"nativescript-angular/nativescript.module";
```
> refactor: stop exporting NativeScriptModule from platform

- nativescript-angular/directives/list-view-comp.ts
- tests/app/tests/list-view-tests.ts
- tests/app/tests/test-utils.ts
- tests/app/tests/value-accessor-tests.ts
Components created in ListView items weren't being properly destroyed. We now destroy the ng embedded view when the element is removed from the visual tree.
Also fixes karma tests broken by latest tns-core-modules.
Fixes #656
> ListView item component leak

- nativescript-angular/platform-common.ts
- nativescript-angular/renderer.ts
- ng-sample/app/app.ts
...instead of `loaded`. Avoid a brief flash of a blank page on slower devices.
Fixes #620
> Init Angular on Page.navigatingTo

- nativescript-angular/platform-common.ts
- nativescript-angular/platform-providers.ts
- nativescript-angular/renderer.ts
Root page provider not crashing anymore.
> fix(platform-providers): Remove a circular import.

- nativescript-angular/directives/action-bar.ts
- nativescript-angular/element-registry.ts
- nativescript-angular/index.ts
- nativescript-angular/view-util.ts
- nativescript-angular/zone-js/dist/zone-nativescript.js
- tests/app/tests/platform-filter-components.ts
- tests/app/tests/property-sets.ts
- tests/app/tests/renderer-tests.ts
- tests/app/tests/test-app.ts
- Update template anchor handling (using comments now)
- Change platform-specific attributes: `android:text` is now `android-text` since Angular 4.0 treats `:` attributes as namespaced.
- Upgrade to zone.js@0.8.4.
> Fix unit tests in release branch

- nativescript-angular/renderer.ts
- nativescript-angular/view-util.ts
- tests/app/tests/platform-filter-components.ts
- tests/app/tests/property-sets.ts
Platform attributes (such as :ios and :android) are passed as
namespaces to the renderer in Angular 4.
Caused by: https://github.com/angular/angular/pull/14874.
This should revert the breaking changes caused by a2fee0ce71d4d2735d9a97f0c09835a116e02ef7.
> fix(renderer): support namespaced attributes

- nativescript-angular/animations/animation-engine.ts
- nativescript-angular/element-registry.ts
- nativescript-angular/view-util.ts
- tests/app/tests/property-sets.ts
this is required because of checks in DomAnimationEngine
Caused by: https://github.com/angular/angular/commit/80075afe8add9d61694638171887e70f2a8ba582
> fix(animations): set nodeType 'element' to newly created views

- nativescript-angular/directives/list-view-comp.ts
Reproducible in the SDK examples Appium tests.
> fix(list-view): Do not access destroyed items' ng views.

- nativescript-angular/directives/action-bar.ts
#comment nodes should be added as views to 'actionBar' since they are anchors for the elements added by structural directive (*ngIf, *ngFor, etc.)
closes #725
> fix(action bar): attach #comment nodes with _addView

- nativescript-angular/directives/list-view-comp.ts
- tests/app/tests/list-view-tests.ts
The fix was not taking into account that view were being recycled
and was causing crashes due to prematurely destroying item views.
Reverts #703 
Related to #656
> fix(list-view): Revert onunload ng view destroy

- nativescript-angular/directives/list-view-comp.ts
- nativescript-angular/trace.ts
We were not recycling item views if the item contained a single
custom component child.
Instead of #740
Fixes #737
> FIX: ListView recycling for wrapped views

- nativescript-angular/router/page-router-outlet.ts
Instantiate child injectors with a providers' map for outlet specific
providers such as Page, PageRoute, ActivatedRoute, etc.
fixes #741
> fix: use providers' map for injectors in page-router-outlet (#744)

- nativescript-angular/package.json
- remove @angular/animations from peerDeps
- bump nativescript-intl version to 3.0
> chore(deps): update nativescript-intl, remove @angular/animations from peerDeps

- nativescript-angular/bin/update-app-ng-deps
This should update all angular packages that the project depends on,
such as @angular/animations and @angular/compiler-cli.
> fix: update-app-ng-deps works for all @angular packages

- nativescript-angular/animations/animation-driver.ts
- nativescript-angular/animations/animation-engine.ts
- nativescript-angular/animations/animation-player.ts
- nativescript-angular/animations/dom-utils.ts
- nativescript-angular/directives/action-bar.ts
- nativescript-angular/directives/list-view-comp.ts
- nativescript-angular/directives/tab-view.ts
- nativescript-angular/element-registry.ts
- nativescript-angular/element-types.ts
- nativescript-angular/index.ts
- nativescript-angular/package.json
- nativescript-angular/renderer.ts
- nativescript-angular/view-util.ts
- ng-sample/app/app.ts
- ng-sample/app/examples/renderer-test.html
- ng-sample/package.json
- tests/app/tests/property-sets.ts
- tests/app/tests/renderer-tests.ts
- tests/package.json
When createText() method of the renderer is called, the newly created CommentNode elements (plain JS objects) are not attached to the visual elements tree.
However, we set a `templateParent` to them in the insertChild method and return it instead of parent in the parentNode method.
Changes:
- Plain JS objects (CommentNode) with just `meta: skipAddToDom` and `templateParent`  are created both for text nodes and comment nodes in the renderer.
- NgView, NgElement, CommentNode and a few other are moved to separate module - `element-types.ts`
- Comments are no longer attached to visual tree.
- Unit tests for NgIfElse and NgIfThenElse added.
> fix(renderer): set templateParent to comment and text nodes

- nativescript-angular/renderer.ts
> fix(renderer): add styles when ViewEncapsulation is None

- nativescript-angular/router/ns-router-link.ts
> fix(ns-router-link): convert clearHistory string to boolean

- nativescript-angular/animations/animation-player.ts
- nativescript-angular/animations/utils.ts
> fix(animations): use parsers from core modules

- nativescript-angular/value-accessors/checked-value-accessor.ts
- nativescript-angular/value-accessors/date-value-accessor.ts
- nativescript-angular/value-accessors/number-value-accessor.ts
- nativescript-angular/value-accessors/selectedIndex-value-accessor.ts
- nativescript-angular/value-accessors/text-value-accessor.ts
- nativescript-angular/value-accessors/time-value-accessor.ts
Somewhat related to #576 and #526
At the moment, selectors only apply to `ngModel` and `formControlName` meaning for Angular reactive forms to work with inputs, they must use `formControlName` within a `formGroup` directive.
I would like to add `[formControl]` to the list of selectors so that reactive forms can be used without a parent `formGroup`.
Rationale:
Say you have a dumb component which implements an input:
```
@Component({
selector: 'my-custom-input',
template: `<TextField [formControl]="control">`
})
export class MyCustomInput {
@Input() control: FormControl
}
```
Which is used by some parent component:
```
@Component({
selector: 'my-parent-component',
template: `<my-custom-input [control]="formGroup.get('someControl')"`
})
export class MyCustomInput {
public formGroup: …
```
> fix(forms): add directives for formControl

- nativescript-angular/package.json
Command:
```
npm install tns-core-modules@next --save --verbose
```
Error:
```
npm WARN nativescript-angular@3.2.0-2017-7-4-1 requires a peer of tns-core-modules@^3.1.0 but none was installed.
/Users/nsbuilduser/workspace/tns-stable-build-testapps-webpack-hello-world-ng/TestApp
`-- (empty)
npm WARN nativescript-angular@3.2.0-2017-7-4-1 requires a peer of tns-core-modules@^3.1.0 but none was installed.
npm verb exit [ 0, true ]
npm verb code 1
```
> chore: update tns-core-modules peer dependency

- nativescript-angular/animations/animation-driver.ts
When querying for `ng-components` (natively represented by
`ProxyViewContainer`s), the container's children are selected instead of
the container itself.
> fix(animations): enable routable animations

- nativescript-angular/router/ns-router-link-active.ts
- ng-sample/app/app.ts
- ng-sample/app/examples/router/router-outlet-test.ts
- ng-sample/app/examples/router/styles.css
Included example usage in the `ng-sample` for `router-outlet-test.ts`.
Implements the `exportAs` feature for the `nsRouterLinkActive` directive. Taken from Angular's repository, this allows you to dynamically access the `isActive` state of the directive to do additional logic outside of just binding classes. 
Also includes optimizations to the update cycle, to prevent unnecessary DOM manipulations as called out here: https://github.com/angular/angular/blob/master/packages/router/src/directives/router_link_active.ts#L124
> feat: add `exportAs` logic for `isActive` on `routerLinkActive` directive

- nativescript-angular/file-system/ns-file-system.ts
- nativescript-angular/resource-loader.ts
- tests/app/tests/xhr-paths.ts
- makes `resolveRelativeUrls` private method of `NSFileSystem`
- extracts fallback resolution to a private method
- makes `ns-file-system` use 4 spaces instead of 2
- add test to assert that resource loader resolver throws for non-existing files that has no fallback resources either
> refactor: resource loader

- nativescript-angular/file-system/ns-file-system.ts
- nativescript-angular/platform.ts
- nativescript-angular/resource-loader.ts
- tests/app/tests/xhr-paths.ts
Implements loading the corresponding `.css` file if `.scss` file was requested but not found.
Resolves: #954
> feat(styling): Allow loading .css files as a fallback if no .scss file is found(#954)

- e2e/renderer/app/action-bar/action-bar-dynamic-items.component.ts
- e2e/renderer/app/action-bar/action-bar-extension.component.ts
- e2e/renderer/app/app-routing.module.ts
- e2e/renderer/app/content-view.component.ts
- e2e/renderer/app/list.component.ts
- e2e/renderer/e2e/action-bar.e2e-spec.ts
- e2e/renderer/e2e/helpers/appium-elements.ts
- e2e/renderer/e2e/helpers/location.ts
- nativescript-angular/directives/action-bar.ts
- nativescript-angular/element-registry.ts
- nativescript-angular/view-util.ts
- refactor(renderer): invoke removeFromQueue for every element
- refactor(action-bar): insert ActionItems at correct positions
ActionBar's insertChild method is now passed a `next` view argument. When the view to insert is an ActionItem, `next` is used to find the correct position to insert the new item.
- refactor(renderer): patch every View with ViewExtensions
When a View is passed through the renderer on insert/remove it's patched
with ViewExtensions for its class. That is done for parent views and for
child views.
fixes #689, fixes #978
> refactor: ActionBar directive and patching of Views in renderer 

- nativescript-angular/value-accessors/date-value-accessor.ts
- nativescript-angular/value-accessors/number-value-accessor.ts
- nativescript-angular/value-accessors/selectedIndex-value-accessor.ts
`view-base`'s `touch` event is not suitable for triggering `ngOnTouch` states for iOS
and is causing several issues, such as overriding the change event.
related #804
related #866
fixes #887
> fix(forms): disable onTouch for date, number and selectedIndex value accessors

- nativescript-angular/http/ns-http.ts
- tests/app/tests/http.ts
This expands support to load local app files when using Angular's `Http` core `request` method. Many apps use the basic `request` api to construct their api calls. This allows the local file request initially implemented [here](https://github.com/NativeScript/nativescript-angular/pull/286) to work the same for calls to `request`.
> feat(Http): Expand support for request on local files

- nativescript-angular/forms/value-accessors/base-value-accessor.ts
- nativescript-angular/forms/value-accessors/checked-value-accessor.ts
- nativescript-angular/forms/value-accessors/date-value-accessor.ts
- nativescript-angular/forms/value-accessors/number-value-accessor.ts
- nativescript-angular/forms/value-accessors/selectedIndex-value-accessor.ts
- nativescript-angular/forms/value-accessors/text-value-accessor.ts
- nativescript-angular/forms/value-accessors/time-value-accessor.ts
merge after https://github.com/NativeScript/NativeScript/pull/4383
> fix(forms): default to unsetValue for value accessors

- tests/app/tests/list-view-tests.ts
- tests/app/tests/modal-dialog.ts
- tests/app/tests/property-sets.ts
Tests fixed:
- Value conversion tests
- Tests that have `done` callback should not return a promise. The result is `Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both.`
> fix(tests): Fix tests: value conversion and async test.

- nativescript-angular/value-accessors/base-value-accessor.ts
All value-accessors have been moved to `forms/value-accessors` folder.
This file is needed for compatibility for people using the `base-value-accessor` frоm the old location.
> fix(forms): Added base-value-accessor.ts for <4.4.0 versions compat

- e2e/router/package.json
- nativescript-angular/router/ns-module-factory-loader.ts
related to NativeScript/NativeScript@011be36
Deprecated code:
NSModuleFactoryLoader is no longer needed for {N} apps.
Before:
```
// app.module.ts
@NgModule({
providers: [
{ provide: NgModuleFactoryLoader, useClass: NSModuleFactoryLoader }
// ...
],
// ...
})
class AppModule { }
```
After:
```
// app.module.ts
@NgModule({
providers: [
// ...
],
// ...
})
class AppModule { }
```
> fix: deprecate NSModuleFactoryLoader in favor of the built-in SystemJsModuleLoader

- nativescript-angular/platform-common.ts
- nativescript-angular/zone-js/dist/zone-nativescript.js
Removes the white screen displayed between the launch screen and the initial page view.
Speeds up roughly 300ms startup times for iOS with Angular.
It turns out the UI that is created on viewWillAppear is just a blank Page (we knew that!)
But then few promises resolve leading to the router navigation and building the actual page UI,
these promises are resolved on the main loop, so the iOS have the time to pass a Window layout and render the blank page.
Then, the interesting part, the iOS framework will not run a second layout immediately but will play the intro animation completely, (having 300ms idle time here) and after that run Window layout. In the SDK examples the ListView will start realising cells on that second layout pass and will consume roughly 250ms.
Draining the micro tasks …
> UI must be created before first render, drainMicroTasks when the first page is created

- nativescript-angular/platform-common.ts
- nativescript-angular/platform.ts
The fake document object that is needed for the angular animations
should be provided both when using the static platform and the dynamic
one.
Can be tested with
https://github.com/nativescript/ns-ng-animation-examples.
```bash
// 1
git clone https://github.com/nativescript/ns-ng-animation-examples
// 2
tns run android --bundle --env.aot
// 3
// Navigate to the first example and expect the button to animate to
opacity 0 when tapped.
```
fixes #1163
> fix(animations): provide fake document object in both AoT and JiT mode

- CONTRIBUTING.md
- DevelopmentWorkflow.md
- README.md
- add more description about the repo in the readme
- add Get Help section in the readme
- move local setup to DevelopmentWorkflow.md
- add contributing.md guide
> docs(readme): Update readme and add Contributing.md

- nativescript-angular/platform-common.ts
Fix: When we navigate back and exit from the application and then trying to restore it - application crashes.
> fix: App crashes on restart in android

- CHANGELOG.md
- nativescript-angular/package.json
Version 5.3.0 bump and change-log updates.
> docs: version bumped to 5.3.0

- nativescript-angular/router/ns-location-strategy.ts
`state` is not guarded before use, but `peekState` may return null.
Appears to have been introduced [here](https://github.com/NativeScript/nativescript-angular/commit/b98da83adb3f5c51ee448fa38a51b7c65274c82e#diff-a7820fa2a2eb0ce14f3f0b8bfc666dd5R49).
Before those changes, `state` was guarded.
May result in the following stack, seen on some older iOS devices (2-3 years) when rapidly navigating:
```
CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:1682:24: ERROR TypeError: undefined is not an object (evaluating 'state.isPageNavigation')
CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:1682:24: ERROR TypeError: undefined is not an object (evaluating 'state.isPageNavigation')
CONSOLE ERROR …
```
> fix(router): state is not guarded before use

- nativescript-angular/common/utils.ts
- nativescript-angular/directives/dialogs.ts
modalParams.closeCallback(...) should not have side effects if called multiple times.
Fixes https://github.com/NativeScript/nativescript-angular/issues/1350
> fix(modal): closeCallback(...) no side effects on multiple calls

- nativescript-angular/router/ns-location-strategy.ts
`_isModalNavigation` should be set to `false` when closing modal view. 
_Note: `_isModalNavigation` is used to mark a state (cached in `cacheByOutlet` dictionary) as the beginning of a navigation inside modal view.  Currently we are lowering this flag only when caching states (navigating further). If there is no further navigation inside the modal view the `_isModalNavigation` will remain `true` which will disturb the clearing of the cached states later on._
> fix(modal): lower isModalNavigation flag when closing modal

- nativescript-angular/router/ns-location-strategy.ts
- nativescript-angular/router/page-router-outlet.ts
- nativescript-angular/trace.ts
During normal usage of a NativeScript app a user can experience instability and unresponsiveness while navigating around an app. This is often experienced when monkeying around as users enjoy doing with mobile apps. Due to extraneous usage of `throw` throughout router handling, this monkeying around of a {N} app would eventually cause one of these `throw`'s to trigger and throwing the app into unstable state and other times just simply crash.
Developers can now properly commence a deep dive debugging sessions by turning tracing on to investigate various UX flows to find suitable fixes within their own apps.
> fix(router): avoiding throw for app stability improvements

- e2e/modal-navigation-ng/app/modal/modal.component.html
- e2e/modal-navigation-ng/e2e/modal-layout.e2e-spec.ts
- nativescript-angular/directives/dialogs.ts
- tests/app/tests/ns-location-strategy.ts
__The problem__: Unable to show modal from another modal if they are not presented from `<p-r-o>` (frameless). There is no available `viewController` (iOS) from whom we can present future modal view.
__The solution__: Use previous modal child view as a `parentView` when presenting new modal. The child view a.k.a `_ngDialogRoot` should have available `viewController` (iOS) created from the previous  modal presentation.
- __modal-navigation-ng__ tests added
Fix: https://github.com/NativeScript/NativeScript/issues/5924
>  fix(dialogs): unable to show nested frameless modal views

- e2e/single-page/package.json
- nativescript-angular/common.ts
- nativescript-angular/nativescript.module.ts
FrameService provider is not singleton when provided through `NativeScriptCommonModule` (since it is imported for every single module in lazy loaded app).
Moving FrameService to `NativeScriptModule` in order to be singleton since it is not stateless (holding cached frames collection).
Fix https://github.com/NativeScript/nativescript-angular/issues/1484
> fix(frame-service): move FrameService provider to NativeScriptModule

- nativescript-angular/platform.ts
`reflect-metadata` is need in JIT mode and needs to be imported before `@angular\core`. It contains calls to `__metadata` and other methods that rely on global `Reflect` to be defined.
Related to #1454
> fix: Import reflect-metadata(needed in JIT mode) before @angular

- e2e/modal-navigation-ng/app/app.css
- e2e/modal-navigation-ng/app/app.ios.css
- e2e/modal-navigation-ng/app/app.routing.ts
- e2e/modal-navigation-ng/app/home/home.component.html
- e2e/modal-navigation-ng/app/layout.component.html
- e2e/modal-navigation-ng/app/layout.component.ts
- e2e/modal-navigation-ng/app/tab.component.ts
- e2e/modal-navigation-ng/e2e/modal.shared.e2e-spec.ts
- e2e/modal-navigation-ng/e2e/shared.e2e-spec.ts
- nativescript-angular/directives/dialogs.ts
Use topmost frame to show modal view when using tabview as a root
_Enable e2e tests that test shared modals when using TabVIew as a root_
>  fix(dialogs): unable to reopen shared modal view when tab as root

- nativescript-angular/router/ns-location-strategy.ts
- nativescript-angular/router/page-router-outlet.ts
- tests/app/tests/modal-dialog.ts
- tests/app/tests/ns-location-strategy.ts
Outlet could be represented by multiple frames when its named and lazy loaded. 
`.goBack()` should be called on the innermost frame (the last one from the collection of outlet frames)
_Note: Every nested named lazy loaded outlet should be wrapped in `NSEmptyOutletComponent` (which is just a regular `<page-router-outlet`>)_
> fix(location-strategy): crash when back on named lazy loaded outlet

- e2e/nested-router-tab-view/app/about/about-nested.component.html
- e2e/nested-router-tab-view/app/about/about-nested.component.ts
- e2e/nested-router-tab-view/app/about/about.component.html
- e2e/nested-router-tab-view/app/about/about.component.ts
- e2e/nested-router-tab-view/app/app.component.html
- e2e/nested-router-tab-view/app/app.routing.ts
- e2e/nested-router-tab-view/app/home/home.component.html
- e2e/nested-router-tab-view/app/shared.module.ts
- e2e/nested-router-tab-view/app/tabs/tabs.component.html
- e2e/nested-router-tab-view/e2e/home-tabs.e2e-spec.ts
- e2e/nested-router-tab-view/e2e/screen.ts
- nativescript-angular/router/ns-location-strategy.ts
- nativescript-angular/router/page-router-outlet.ts
__The Problem:__ Currently navigating to `[nsRouterLink]="[url/url2/url3]"`, when "/url3" should be loaded child in nested 'primary' p-r-o, won't work. It will work if navigating to outlet `[nsRouterLink]="["url/url2", { outlets: { primary:["url3]}}]"`
e2e test added
> fix(router): handle nested primary p-r-o

- e2e/nested-router-tab-view/app/app.component.html
- e2e/nested-router-tab-view/app/app.routing.ts
- e2e/nested-router-tab-view/app/custom-tabs/custom-tabs.component.html
- e2e/nested-router-tab-view/app/custom-tabs/custom-tabs.component.ts
- e2e/nested-router-tab-view/app/custom-tabs/custom-tabs.module.ts
- e2e/nested-router-tab-view/app/login/login.component.html
- e2e/nested-router-tab-view/app/player/player-detail.component.html
- e2e/nested-router-tab-view/app/player/players.component.html
- e2e/nested-router-tab-view/app/player/players.component.ts
- e2e/nested-router-tab-view/app/team/team-detail.component.html
- e2e/nested-router-tab-view/app/team/teams.component.html
- e2e/nested-router-tab-view/e2e/custom-tabs.e2e-spec.ts
- e2e/nested-router-tab-view/e2e/screen.ts
- nativescript-angular/router/ns-location-strategy.ts
- nativescript-angular/router/ns-route-reuse-strategy.ts
- nativescript-angular/router/page-router-outlet.ts
- nativescript-angular/router/router-extensions.ts
- tests/app/tests/ns-location-strategy.ts
Extending `LocationState` with `Frame` property which holds the `Frame` that initiated the navigation for the  given `LocationState`. __Back__ in parent Outlet should take care of its children states (remove all states until the current `Frame` that goes back is reached).
Various bug with nested primary `<page-router-outlets>` where reported from both Kinvey Shared Application and the North Star project.
> fix(location-strategy): extend support for nested primary outlets

- nativescript-angular/dom-adapter.ts
- nativescript-angular/platform-common.ts
- nativescript-angular/platform.ts
Always register the `NativeScriptDomAdapter`.
It is used for console.logging when router tracing is enabled.
resolves #650 even when bundling application with webpack.
> fix: Router tracing does not work with webpack

- nativescript-angular/router/router.module.ts
- tests/app/tests/router-module-tests.ts
- tests/package.json
There are a couple of flaws in the `NativeScriptRouterModule`:
1. Routing services (`LocationStrategy`, `RouteReuseStrategy`, `RouterExtensions`, etc.) are provided **inside** the `NativeScriptRouterModule` module. This might cause issues with lazy loaded modules which import `NativeScriptRouterModule`.
2. The `forRoot()` and `forChild()` methods of `NativeScriptRouterModule` do not export the actual `NativeScriptRouterModule` (only the stock `RouterModule` form angular). This means that you will have to import both `NativeScriptRouterModule.forRoot/forChild(routes)` and `NativeScriptRouterModule` in every module.
1. Routing services are exported **only** in the module returned from `NativeScriptRouterModule.forRoot(), similar to [Angular …
> fix(router): routing services should be provided in forRoot only

- e2e/single-page/app/app.css
- e2e/single-page/app/app.module.ts
- e2e/single-page/app/second/modal/modal.component.html
- e2e/single-page/app/second/modal/modal.component.ts
- e2e/single-page/app/second/second.component.ts
- e2e/single-page/e2e/tests.e2e-spec.ts
- nativescript-angular/directives/dialogs.ts
- nativescript-angular/package.json
- nativescript-angular/router/ns-location-strategy.ts
- nativescript-angular/router/page-router-outlet.ts
Modify location-strategy to better handle `<router-outlets>` and modal views:
- `_beginModalNavigation` method shouldn't set `currentOutlet` to null when no outlet for the given Frame found.
- `clearOutlet` method: Do not remove outlet, from outlets collection, who belongs to `<router-outlet>` since it doesn't have any frames[]
- `findOutlet` method should always respect the current `_modalNavigationDepth` when searching for outlet, since there could be 2 or more identical outlets on different modal views ( _primary-> (modal:primary)->(modal2->primary)_) 
- make `findOutletByModal ` private, since it won't be used outside location-strategy anymore 
Fix https://github.com/NativeScript/nativescript-angular/issues/1735
> fix(location-strategy): crash on going back with router-outlet after closing modal

- build-docs.sh
- nativescript-angular/package.json
- nativescript-angular/tsconfig.typedoc.json
> NS Angular - API Ref Build

- e2e/modal-navigation-ng/app/navigation/basic.navigation.component.ts
- e2e/modal-navigation-ng/package.json
- e2e/modal-navigation-ng/references.d.ts
- nativescript-angular/directives/dialogs.ts
Refactored [this](https://github.com/NativeScript/nativescript-angular/pull/1767) and [this](https://github.com/NativeScript/nativescript-angular/pull/1769) PRs into a merged PR and also added "test case" to the _modal-navigation-ng_ application for future e2e test.
As per this issue https://github.com/NativeScript/nativescript-angular/issues/1709 it's currently not possible to use an ios popover style modal.
The current exposed options for showModal differs from the options available in the core.
I've added a couple of new options to `ModalDialogOptions`
- sourceView - this is required as normally you would use `viewContainerRef` but if you want to attach a popover to a button for example you need to pass in the button element.
- ios - allows you to use `presentationStyle: …
> Update modal to allow use of ios presentationStyle

- nativescript-angular/router/ns-platform-location.ts
- nativescript-angular/router/router.module.ts
Minor changes that came up during a knowledge sharing session
> refactor: minor changes after review

- nativescript-angular/platform-common.ts
- nativescript-angular/router/page-router-outlet.ts
- ~Tests for the changes are included.~ **Don't see how**
The application module isn't destroyed when the application exitEvent is triggered.
This causes the previous instance of the nativescript-angular app to be running in a sleep state and `ngOnDestroy()` on it's compoments, services etc. are not called as expected.
Adds an event listener for the `exitEvent` in the `NativeScriptPlatformRef` which destroys the `lastModuleRef` which triggers `ngOnDestroy()` as expected.
Fixes #923
> fix(NativeScriptPlatformRef): Destroy lastModuleRef on exitEvent

- nativescript-angular/tsconfig.json
The usage of short imports, e.g, `import * as Page from "ui/page"`
instead of `import * as Page from "tns-core-modules/ui/page"` is
*deprecated* since {N} 5.2.
> chore(tsconfig): remove path resolution for short imports (`ui/page`)

- .gitignore
- e2e/config/mocha.opts
- e2e/modal-navigation-ng/app/navigation/basic.navigation.component.ts
- e2e/modal-navigation-ng/e2e/modal.shared.e2e-spec.ts
- e2e/modal-navigation-ng/e2e/screens/screen.ts
> chore: add new test for #1771

- nativescript-angular/router/page-router-outlet.ts
- nativescript-angular/view-util.ts
This reverting the recursive removeChild implemented in #1740 by @m-abs 
We found the following issues and decided to revert the change until they are resolved:
1. #1818 - Error: `Cannot read property 'textTransform' of undefined` in `createSpannableStringBuilder`
2. Crash in [nativescript-sdk-examples-ng](https://github.com/NativeScript/nativescript-sdk-examples-ng) with tab view. To reproduce go to : `TabView` -> `Basic` -> `[back]`. You get a crash (in console) and cannot navigate any more
> fix: revert recursive remove -causing crashes

- nativescript-angular/package.json
We need to bump this version so otherwise the version could be mismatch.
> chore: bump version to 7.3.0

- nativescript-angular/renderer.ts
- tests/app/tests/renderer-tests.ts
I can't run the unit tests, so I couldn't write a test for this fix.
`:host` selector only works for on first instance of a component.
This is caused by `_nghost-%COMP%`-property only being applied when the `EmulatedRenderer` is created for a type, but not when it is reuse.
The `_nghost-%COMP%`-property is applied when the `EmulatedRenderer` is reused.
Fixes #1845
> fix(1845): CSS special selector ":host" only work first time

- nativescript-angular/view-util.ts
The `_applyXmlAttribute` is removed - it is no longer needed.
> refactor: remove deprecated API usage

- tests/karma.conf.js
> tests: mocha reporter and include ts files

- e2e/nested-router-tab-view/e2e/home-tabs.e2e-spec.ts
This is related to the [tns-core-modules animations overhaul intiative](https://github.com/NativeScript/NativeScript/pull/7925) (removing Animators in favor of androidx Transitions)
__Test case__: navigating from Page with 3 nested frames and back crashes with `IllegalArgumentException: parameter must be a descendant of this view` only from these commented appium tests (does not reproduce with manual testing).
This is fixed in androidx.fragment:fragment:1.2.0 and tests must be uncommented when migrating to it.
> tests: comment tabs tests partially

- nativescript-angular/bin/update-app-ng-deps
Otherwise, Travis CI fails after using scoped deps like:
https://travis-ci.org/NativeScript/nativescript-camera/jobs/601011779
> fix: use cwd() as backup for getting path

- e2e/animation-examples/tsconfig.json
- e2e/modal-navigation-ng/tsconfig.json
- e2e/nested-router-tab-view/app/app.module.ts
- e2e/nested-router-tab-view/app/modal-second/modal-second.component.html
- e2e/nested-router-tab-view/tsconfig.json
- e2e/renderer/tsconfig.json
- e2e/routable-animations/tsconfig.json
- e2e/router-tab-view/app/app.module.ts
- e2e/router-tab-view/tsconfig.json
- e2e/router/tsconfig.json
- e2e/single-page/tsconfig.json
- e2e/tests-app-ng/tsconfig.json
- nativescript-angular-package/directives/templated-items-comp.ts
- nativescript-angular/directives/index.ts
- ng-sample/app/app.ts
when adding dependencies in `package.json` with `file: ...`, the packages in `node_modules` are not flattened (`@nativescript/angular` is not placed in `node_modules`' root, but under `nativescript-angular`'s `node_modules`) and `tns build ... --env.aot` command fails because paths are not resolved. That is why we need:
```json
"./node_modules/nativescript-angular/node_modules/*"
```
added as path in tsconfigs
> fix: local development workflow errors

- nativescript-angular/directives/dialogs.ts
- nativescript-angular/platform-providers.ts
- nativescript-angular/router/ns-location-strategy.ts
- nativescript-angular/testing/src/util.ts
Deprecated with https://github.com/NativeScript/NativeScript/pull/7911 in favor of static Frame.topmost().
> refactor: deprecated topmost() usage

- e2e/tests-app-ng/app/lazy/lazy.component.css
- e2e/tests-app-ng/app/lazy/lazy.component.html
- e2e/tests-app-ng/app/lazy/lazy.component.ts
- e2e/tests-app-ng/package.json
- e2e/tests-app-ng/tsconfig.json
Modal window in iOS 13 is transparent.
Modal window in iOS 13 is not transparent. In iOS 13 the style of the modals has changed and we need ot explicitly set the `backgroundColor` of the first element that is passed to `showModal`
Resolves https://github.com/NativeScript/nativescript-angular/issues/2012
> chore: add background color to modal in example

- build/pack-scripts/pack-compat.ts
As a summary for the script:
Use this script to pack .tgz for nativescript-angular package. The first passed param can be:
1. Path to .tgz file - in this case the script replaces the scoped dependency (@nativescript/angular) with it in the package.json file. Then packs.
2. Tag or exact version - in this case the script does `npm install --save-exact` to save the exact version (in case if tag). Then packs.
3. `auto-version` - this is interpreted by getting version from the scoped package.json file (nativescript-angular folder).
> chore: rework build script for release to get automatically the version

- nativescript-angular/resource-loader.ts
Since https://github.com/NativeScript/NativeScript/pull/7671 `File. readText()` no longer resolves synchronously. This causes a `Bootstrap promise didn't resolve` error on startup for playground projects.
Use `readTextSync()` method in the `FileSystemResourceLoader` so that resources are resolved synchronously again.
> fix: make FileSystemResourceLoader sync

- CHANGELOG.md
- build/pack-scripts/pack-compat.ts
- nativescript-angular-package/forms/value-accessors/base-value-accessor.ts
- nativescript-angular-package/lang-facade.ts
- nativescript-angular-package/package.json
- nativescript-angular/package.json
fix: add exports for backwards compatibility
addresses https://github.com/nstudio/nativescript-checkbox/issues/118 and issues described [here](https://github.com/NativeScript/nativescript-dev-webpack/pull/1088)
> Tbozhikov/release 8.20.1

- CHANGELOG.md
- nativescript-angular-package/app-host-view.ts
- nativescript-angular-package/common.ts
- nativescript-angular-package/common/detached-loader.ts
- nativescript-angular-package/common/utils.ts
- nativescript-angular-package/dom-adapter.ts
- nativescript-angular-package/package.json
- nativescript-angular-package/schema-registry.ts
- nativescript-angular/package.json
fixes in `nativescript-angular` package for backwards compatibility, addresses #2059
> Release 8.20.2

- nativescript-angular/platform-common.ts
Can be reproduced with the hello-word template on Android:
1. Create an app an run it
1. Make a change in `item.service.ts` to trigger HMR
1. Exit the app with the back button
1. Run the app again - it is blank
The app is rendered as expected after re-launch.
The actual problem fixed is that the `launchCallback` was using an outdated instance of `AppHostView` instead of creating new host view on every launch.
> fix(hmr): After HMR app is blank when re-launched

- e2e/modal-navigation-ng/app/home/home.component.ts
- nativescript-angular/nativescript.module.ts
- nativescript-angular/platform-providers.ts
- nativescript-angular/router/page-router-outlet.ts
To detect navigation we have to manually inject page, listen to events and handle the subscriptions.
Introduces a `PageService` that has:
- `page`: reference to the current page
- `inPage: boolean`: Page is the currently displayed page
- `inPage$: Observable<boolean>`: will emit true/false when entering/leaving page
- `pageEvents$: Observable<NavigatedData>`: observable of page events (use with `filter` operator)
example implementation:
```typescript
export class DemoComponent {
subscribed = false;
constructor(pageService: PageService) {}
ngOnInit() {
this.subscribeToEvents();
this.pageService.inPage$.subscribe(
(inPage) => inPage ? this.subscribeToEvents() : this.clearSubscriptions();
)
}
ngOnDestroy() {
this.clearSubscriptions();
}
subscribeToEvents() {
if (this.subscribed) return; …
```
> feat: introduce PageService

- e2e/tests-app-ng/app/app.routes.ts
- e2e/tests-app-ng/app/list-view/list-view-main-page.component.ts
- e2e/tests-app-ng/app/list-view/list-view-nested-segmented-bar-page.component.ts
- nativescript-angular/view-util.ts
I ran the appium tests but it couldn't hurt to double check these too. In addition to this, I have also provided a test in the `test-app-ng` application.
Manually tested on both iOS and Android.
In a class with a member that contains an array of `SegmentedBarItem`s, using this to populate a `SegmentedBar` in a `listView`.
When the `listView` has scrolled below the view of the `SegmentedBar` and the items driving the `listView` change, scrolling back to the `SegmentedBar` causes a hard crash on Android.
Introduce a simple check as to whether a new value on `setPropertyInternal` is an array, if so, check and unreference any of the items references to a `parent` & `parentNode`.
The demo page contains a simple list containing a `SegmentedBar` as an item, scrolling to the bottom of the list …
> fix(listview) segmentedbar crash

- e2e/animation-examples/app/app.module.ts
- e2e/animation-examples/app/main.ts
- nativescript-angular/platform-common.ts
> feat(bootstrap): support for async APP_INITIALIZER and animated launch screens

- nativescript-angular/tslint.json
A couple of rules were deleted in pull request #2179, but they were actually just renamed and not deprecated.
Two rules re-added.
> test: re-add tslint rules

- e2e/animation-examples/tsconfig.tns.json
- e2e/tests-app-ng/app/modal/modal-dialogs/modal-dialog.component.ts
- e2e/tests-app-ng/package.json
- e2e/tests-app-ng/tsconfig.json
- e2e/tests-app-ng/tsconfig.tns.json
- nativescript-angular/router/ns-router-link-active.ts
- nativescript-angular/router/ns-router-link.ts
closes https://github.com/NativeScript/nativescript-angular/issues/2224
> fix(router): link active directive

- nativescript-angular/common/detached-loader.ts
Detached Loader (DetachedContainer) creates components in place, attaching to a detached ProxyViewContainer and then moving the native views to their appropriate position:
```
Application
|----AppComponent
|      |---------- Component1
|                       |---------- ListView1
|                       |---------- DetachedContainer (not actually added to the DOM!)
|                                        |---------- ModalView/ListView item/etc (Ng view attached to DetachedContainer, native view attached to modal window/ListView1)
```
Detached Loader will instantiate components without adding them to the DOM at all, but instead attaching the angular view to the ApplicationRef (enabling change detection). This also fixes issues where modals opened inside a `OnPush` component would not be …
> fix(detached-loader): completely deatch components

- nativescript-angular/renderer.ts
When using ViewEngine, insertBefore is always called with the result of `nextSibling`. On Ivy this has changed so the View itself is returned. The current implementation will ignore view order when running with ivy
Support view references to be passed to insertBefore, fixing positioning issues.
Fixes #2176 #2249.
> fix(ivy): support view references in insertBefore

- nativescript-angular/element-registry.ts
- nativescript-angular/renderer.ts
- nativescript-angular/view-util.ts
Ordering can be erratic when nesting ng-containers and templates. This is due to `previousSibling` not being implemented and comment nodes not being properly respected
```html
<ng-container>
<Label text="1" *ngIf="show"></Label>
<Label text="2" *ngIf="show"></Label>
</ng-container>
```
will render:
2
1
The node list is now doubly linked (`previousSibling` and `nextSibling`), allowing for faster processing of previousSibling and respecting the positioning of commentnodes.
```html
<ng-container>
<Label text="1" *ngIf="show"></Label>
<Label text="2" *ngIf="show"></Label>
</ng-container>
```
will render
1
2
> fix(renderer): order not preserved

- nativescript-angular/view-util.ts
The angular renderer doesn't support adding views to the first position:
```html
<StackLayout>
<ng-container *ngIf="someBoolean">
<Label text="I come first"></Label>
<Label text="I come second" *ngIf="someOtherBoolean"></Label>
</ng-container>
</StackLayout>
```
Result:
```
I come second
I come first
```
This is because the renderer treats not having a previous element as needing to append.
1. ViewContainer at position 0. StackLayout is empty, StackLayout now contains ViewContainer at 0
2. add ng-container before ViewContainer (no previous element). **StackLayout now contains [VC,ng-container] (should be the other way around).** Doubly linked list references are now broken.
3. add "I come first" before ng-container. [VC, "I come first", ng-container]
4. add "I come second" before …
> fix(renderer): dynamic views can't be prepended

- nativescript-angular/directives/index.ts
The `TEMPLATED_ITEMS_COMPONENT` injection token is missing from the export, thus preventing ability to create plugins/other components that extend the `TemplatedItemsComponent`
The `TEMPLATED_ITEMS_COMPONENT` is re-exported
> fix: Export injection token used by plugins

- nativescript-angular/element-registry.ts
Adds `RootLayout` to element-registry. This is the changes required for `RootLayout` to work with Angular (https://github.com/NativeScript/NativeScript/pull/8980). This is dependent on Nativescript's `release/8.0.0` branch
> feat: add RootLayout to element-registry

- nativescript-angular/router/ns-router-link-active.ts
- nativescript-angular/router/ns-router-link.ts
We were using an older implementation of routerLinkActive which was not ivy compatible
Updates to latest angular routerLinkActive implementation
Fixes #2321.
> fix(ivy): nsRouterLinkActive works on nsRouterLink

- nativescript-angular/testing/src/polyfills.ts
- nativescript-angular/testing/src/public_api.ts
Angular 11 introduced a regression where they check `instanceof Node`, but Node is not polyfilled by Nativescript so it errors out.
Node is polyfilled with a dummy class.
Fixes #2311.
> fix: polyfill global.Node for angular testing
