README.md
=> Update README to reflect correct numbers on steps

src/nativescript-angular/application.ts
Root page for now. Will extend the page router outlet, so it injects child pages to activated components.
//cc @vakrilov
=> Inject Page instance to all components.

src/nativescript-angular/router.d.ts, src/nativescript-angular/router.ts
Use `nativescript-angular/router` as the recommended entrypoint
=> Add typings for router exports.

ng-sample/.vscode/launch.json, ng-sample/.vscode/settings.json, ng-sample/app/app.ts, ng-sample/app/examples/action-bar/action-bar-test.ts, src/nativescript-angular/application.d.ts, src/nativescript-angular/application.ts, src/nativescript-angular/directives/action-bar.ts, src/nativescript-angular/directives/ns-directives.ts, src/nativescript-angular/element-registry.d.ts, src/nativescript-angular/element-registry.ts, src/nativescript-angular/router/page-router-outlet.ts, src/nativescript-angular/view-util.ts, tests/app/tests/property-sets.ts
Resolves #55 
Ping: @hdeshev @nsndeck
=> Action bar directives

ng-sample/package.json, package.json, src/nativescript-angular/platform-providers.ts, src/nativescript-angular/router/page-router-outlet.ts, tests/package.json
Only minor changes to router imports needed.
=> Upgrade to beta 9

ng-sample/app/examples/navigation/navigation-test.ts, src/nativescript-angular/element-registry.ts, src/nativescript-angular/router/page-router-outlet.ts, tests/app/tests/router.ts, tests/app/tests/test-app.ts, tests/app/tests/test-utils.ts
=> Allow page outlet ate root and clean up the visual tree

ng-sample/.vscode/settings.json, ng-sample/app/examples/action-bar/action-bar-test.ts, src/nativescript-angular/view-util.ts, tests/app/tests/property-sets.ts
=> Allow settingnested properties

ng-sample/package.json, package.json, src/nativescript-angular/renderer.ts, tests/package.json
Fix an issue with moving components to different pages on navigation.
=> Use application styles in component renderers

README.md
Doesn't seem to be true anymore.
=> Remove line about submodules from README

ng-sample/app/app.ts, ng-sample/app/examples/navigation/router-outlet-test.css, ng-sample/app/examples/navigation/router-outlet-test.ts, src/nativescript-angular/router/ns-router-link.ts
=> Implemented isRouteActive property of nsRouterLink

ng-sample/app/examples/action-bar/action-bar-test.ts, ng-sample/app/performance/benchmark.ts, ng-sample/package.json, package.json, src/nativescript-angular/application.ts, src/nativescript-angular/renderer.ts, src/nativescript-angular/router/page-router-outlet.ts, tests/package.json
Update to angular-beta-14
Thanks to @NathanWalker for doing most of the work in #154
=> chore: update to beta.14

ng-sample/app/app.ts, src/nativescript-angular/application.d.ts, src/nativescript-angular/application.ts
=> Return Promise form nativeScriptBootstrap

src/nativescript-angular/element-registry.ts, tests/app/tests/renderer-tests.ts, tests/app/tests/test-app.ts
=> Support for kebab-case-component-tags

tests/app/main.ts, tests/app/snippets/gestures.component.ts, tests/app/snippets/gestures.component.xml
Code snippets for gestures article
=> Gestures snippets

tests/app/main.ts, tests/app/snippets/layouts.component.ts, tests/app/snippets/layouts.component.xml, tests/app/tests/renderer-tests.ts, tests/app/tests/snippets.ts
=> Layout snippets

src/nativescript-angular/element-registry.ts
Added SegmentedBarItem to element registry. And now `SegmentedBarItem` could be added via HTML.
```HTML
<SegmentedBar>
<SegmentedBarItem title="Waiting" ></SegmentedBarItem>
<SegmentedBarItem title="Done" ></SegmentedBarItem>
</SegmentedBar>
```
=> Added SegmentedBarItem to element registry.

src/nativescript-angular/directives/list-view-comp.ts
Fix ListView to work as a direct child of a Page.
=> Fix ListView to work as a direct child of a Page.

.gitignore, gruntfile.js, package.json, src/nativescript-angular/hooks/before-livesync.js, src/nativescript-angular/hooks/hook-helper.js, src/nativescript-angular/postinstall.js
Add tns livesync hooks and install script.
=> Disable single-page livesync updates

ng-sample/app/app.ts, ng-sample/app/examples/action-bar/action-bar-test.ts, ng-sample/package.json, src/nativescript-angular/directives/action-bar.ts
=> Fix crashing ActionBar in IOS

tests/app/tests/third-party-view.ts, tests/app/tests/third-party.ts
=> Third party code snippets.

src/nativescript-angular/directives/list-view-comp.ts, src/nativescript-angular/directives/tab-view.ts, src/nativescript-angular/value-accessors/selectedIndex-value-accessor.ts, tests/app/tests/value-accessor-tests.ts
Added selectedIndex as input in order to enable scenarios with selectedIndex different from first one.
=> TabView selectedIndex to work with binding.

src/nativescript-angular/directives/list-view-comp.ts
Fix log spell from "Reusing **exisiting** view" to "Reusing **existing** view".
=> Fix spell mistake from exisiting to existing

nativescript-angular/router/page-router-outlet.ts
Resolves #257 
ping @NickIliev
=> Fixed: IOS - crash canceling swipe-back navigation

nativescript-angular/renderer.ts
The side drawer component code will change and it won't rely on this hack.
=> Revert the hack for the side drawer component.

nativescript-angular/view-util.ts
We should delete current classes before setting the new values.
=> Fixed problem with setting class attribute.

nativescript-angular/package.json
=> Remove peer dependency on tns-core-modules

nativescript-angular/application.ts
Closes #311 
There is a limitation in IOS: Any code executed after `application.run()` will not be executed in IOS. As `application.run()` is called inside `nativescriptBootstrap` there is no point to return promise from this method - the promise can never be consumed.
The code that is to be executed on app startup can be moved inside the app main component.
=> Don't return promise in nativescriptBootstrap

nativescript-angular/animation-driver.ts, nativescript-angular/animation-player.ts, nativescript-angular/platform-providers.ts, nativescript-angular/renderer.ts
=> chore: Remove ANIMATION_DRIVER token

nativescript-angular/animation-player.ts
=> Fix: Rotate transform in animations not working

nativescript-angular/directives/tab-view.ts, ng-sample/app/examples/tab-view/tab-view-test.html
Added title and iconSource properties for TabViewDirective in order to support binding both properties to a view model.
=> Added title and iconSource properties to TabViewDirective.

.travis.yml, build/travis-scripts/add-publishConfig.js, tests/app/tests/http.ts
Added @next build functionality.
=> Added @next build functionality to travis.

nativescript-angular/application.ts
https://github.com/NativeScript/nativescript-cli/issues/1958
ping @vakrilov
=> Fixed: CSS is not automatically livesynced in angular apps

nativescript-angular/package.json, nativescript-angular/router/ns-router-link-active.ts, nativescript-angular/router/ns-router-link.ts, nativescript-angular/router/ns-router.ts, ng-sample/app/app.ts, ng-sample/app/examples/router/clear-history-test.ts, ng-sample/app/examples/router/clear-history.component.html, ng-sample/app/examples/router/router-outlet-test.ts, ng-sample/app/examples/router/styles.css
=> nsRouterLinkDirective 

nativescript-angular/router/router-extensions.ts
=> canGoBackToPreviousPage method fixed

nativescript-angular/element-registry.ts
Will enable using the flex box in templates:
``` XML
<StackLayout>
<Label text="Tap the button" class="title"></Label>
<Button text="TAP" (tap)="onTap()"></Button>
<FlexboxLayout>
<Button text="B1"></Button>
<Button text="B2" flexGrow="1"></Button>
<Button text="B3"></Button>
</FlexboxLayout>
<Label [text]="message" class="message" textWrap="true"></Label>
</StackLayout>
```
=> register the FlexboxLayout element

nativescript-angular/value-accessors/checked-value-accessor.ts, nativescript-angular/value-accessors/date-value-accessor.ts, nativescript-angular/value-accessors/number-value-accessor.ts, nativescript-angular/value-accessors/selectedIndex-value-accessor.ts, nativescript-angular/value-accessors/text-value-accessor.ts, nativescript-angular/value-accessors/time-value-accessor.ts, ng-sample/app/examples/renderer-test.html
=> Extend value-accessors selectors

.travis.yml, nativescript-angular/dom-adapter.ts, tests/e2e-tests/multi-page-routing.js, tests/e2e-tests/single-page-routing.js, tests/package.json
Merged the Appium 1.6 upgrade as well, since Travis started failing with 1.5
Fixes #517
=> Hdeshev/ng 2.1.2

ng-sample/.vscode/launch.json, ng-sample/app/examples/router/login-test.ts, tests/app/snippets/navigation/route-params.ts
Example using `ResolveGuard` and `PageRoute` to resolve and retrieve parameters.
=> Reslove guard added to login example

nativescript-angular/dom-adapter.ts, nativescript-angular/index.ts, nativescript-angular/nativescript.module.ts, nativescript-angular/platform-common.ts, nativescript-angular/platform-static.ts, nativescript-angular/platform.ts, nativescript-angular/router/ns-router-link-active.ts, nativescript-angular/router/page-router-outlet.ts
Split dynamic and static platforms to ease bundling in ahead-of-time compiled apps
=> Optimize platfroms for AOT

nativescript-angular/dom-adapter.ts, nativescript-angular/index.ts, nativescript-angular/nativescript.module.ts, nativescript-angular/platform-common.ts, nativescript-angular/platform-static.ts, nativescript-angular/platform.ts, nativescript-angular/router/ns-router-link-active.ts, nativescript-angular/router/page-router-outlet.ts, tests/app/lazy-load-main.ts, tests/app/lazy-loaded.module.ts, tests/app/main.ts, tests/e2e-tests/lazy-load-routing.js
=> Fix(page-router-outlet): make page-router-outlet lazy-loadable

nativescript-angular/directives.ts, nativescript-angular/directives/list-view-comp.ts, nativescript-angular/router/page-router-outlet.ts, ng-sample/app/app.ts, ng-sample/app/examples/list/styles.css, ng-sample/app/examples/list/template-selector.ts, tests/app/snippets/navigation/page-outlet.ts, tests/app/snippets/navigation/router-outlet.ts, tests/app/tests/list-view-tests.ts, tests/app/tests/test-app.ts, tests/package.json
=> List view templates

tests/npm-shrinkwrap.json
Hopefully no more suprrises on Travis.
=> Shrinkwrap tests dependencies to avoid Appium surprises

tests/app/snippets/list-view/template-selector.component.html, tests/app/snippets/list-view/template-selector.component.ts, tests/app/snippets/navigation/page-outlet.ts, tests/app/tests/snippets.ts
Snippets for ListView documentation
=> LIstView template selector snippets

ng-sample/app/examples/router/login-test.ts
Simple typo fix from onReslove to onResolve
=> Fix typo from onReslove to onResolve

.travis.yml, build/generate-value-accessor-selector.js, nativescript-angular/value-accessors/base-value-accessor.ts, nativescript-angular/value-accessors/checked-value-accessor.ts, nativescript-angular/value-accessors/date-value-accessor.ts, nativescript-angular/value-accessors/number-value-accessor.ts, nativescript-angular/value-accessors/selectedIndex-value-accessor.ts, nativescript-angular/value-accessors/text-value-accessor.ts, nativescript-angular/value-accessors/time-value-accessor.ts, tests/app/tests/value-accessor-tests.ts
=> Value accessors using static selectors now.

tests/app/snippets/navigation/config-snippets.ts
Fixed `router-bootstrap` snippet
=> Snippets tag fixed

nativescript-angular/lang-facade.ts
=> chore(cleanup): Delete unused export in lang-facade

nativescript-angular/package.json
=> fix(dependencies): remove repeated codelyzer dev-dep

nativescript-angular/bin/update-app-ng-deps, nativescript-angular/bin/update-app-ng-deps.cmd, nativescript-angular/package.json
Add a tool that will update all application dependencies to the
correct Angular version that the current plugin requires.
Call with:
```bash
$ ./node_modules/.bin/update-app-angular-deps
```
=> feat(dependencies): Upgrade Angular dependencies.

.travis.yml
Until we are ready to go back with `next`
=> chore(travis): Use internal-preview as the npm dist tag.

nativescript-angular/package.json, nativescript-angular/tsconfig.json, ng-sample/package.json, ng-sample/tsconfig.json, tests/package.json, tests/tsconfig.json
Update for latest modules 3.0. Add path mappings to tsconfig files.
=> No ambient modules

nativescript-angular/animation-driver.ts, nativescript-angular/animation-player.ts, nativescript-angular/package.json, nativescript-angular/platform-common.ts, nativescript-angular/platform-providers.ts, nativescript-angular/platform-static.ts, nativescript-angular/platform.ts, nativescript-angular/router/ns-location-strategy.ts, nativescript-angular/tsconfig.json, nativescript-angular/view-util.ts, ng-sample/app/examples/renderer-test.ts, ng-sample/package.json, ng-sample/tsconfig.json, tests/app/tests/test-config.ts, tests/app/tests/test-utils.ts, tests/npm-shrinkwrap.json, tests/package.json, tests/tsconfig.json
Upgrades the renderer, animations, TypeScript projects.
=> tns-core-modules 3.0 support

nativescript-angular/zone-js/dist/zone-nativescript.js
Syncing with https://github.com/NativeScript/zone.js/tree/v0.8.4
=> Upgrade to zone.js 0.8.4

nativescript-angular/router/ns-router-link.ts
=> fix(ns-router-link): navigate with urlTree

CHANGELOG.md, nativescript-angular/package.json
docs: update CHANGELOG for 1.5.1
=> release: cut the 1.5.1 release

nativescript-angular/router/page-router-outlet.ts
Instantiate child injectors with a providers' map for outlet specific
providers such as Page, PageRoute, ActivatedRoute, etc.
fixes #741
=> fix: use providers' map for injectors in page-router-outlet

CHANGELOG.md
=> docs: update 3.0.0 changelog

nativescript-angular/dom-adapter.ts
caused by https://github.com/angular/angular/pull/15256
fixes #831
=> fix(dom-adapter): add fake implementation for getUserAgent

nativescript-angular/directives/action-bar.ts
=> fix(action-bar): ignore InvisibleNodes when adding title

e2e/renderer/package.json, e2e/router/package.json
Fix the current version of the `nativescript-dev-appium` plugin as changes are expected.
=> chore(tests): Fix current version of ns-dev-appium

CODE_OF_CONDUCT.md, LICENSE, nativescript-angular/LICENSE
Changes on LICENSE and CODE_OF_CONDUCT files, made by automatic tool
=> update LICENSE and CODE_OF_CONDUCT.md

tests/app/snippets/list-view/template-selector.component.ts
show the full code snippet - ListView Multiple Item Templates
=> docs: show the full code snippet - ListView Multiple Item Templates

.travis.yml, tests/package.json
=> chore: use next in test app

CHANGELOG.md, nativescript-angular/package.json
Should be merged with `rebase and merge`.
=> Changelog for 6.0

CHANGELOG.md, nativescript-angular/package.json
See the changelog for changes. This PR should be merged with rebase and merge.
=> release: 6.0.6

nativescript-angular/nativescript.module.ts
fixes https://github.com/NativeScript/nativescript-angular/issues/1417
=> fix: mark NativeScriptModule as root injector

nativescript-angular/directives/index.ts, nativescript-angular/directives/list-view-comp.ts, nativescript-angular/directives/templated-items-comp.ts
Rebased version of #1231 by @PeterStaev 
Resolves #1222
=> refactor: standardize template items component

nativescript-angular/directives/action-bar.ts
The tests should be updated as well.
party resolves #1535
=> refactor: remove short imports of modules from `tns-core-modules`

CHANGELOG.md, nativescript-angular/package.json
=> release: cut the 6.2.0 release

nativescript-angular/directives/templated-items-comp.ts, tests/app/tests/list-view-tests.ts
https://github.com/NativeScript/nativescript-angular/issues/1733
=> fix(list-view): add support for "defaultTemplate"

e2e/single-page/app/app.css, e2e/single-page/app/app.module.ts, e2e/single-page/app/second/modal/modal.component.html, e2e/single-page/app/second/modal/modal.component.ts, e2e/single-page/app/second/second.component.ts, e2e/single-page/e2e/tests.e2e-spec.ts, nativescript-angular/directives/dialogs.ts, nativescript-angular/package.json, nativescript-angular/router/ns-location-strategy.ts, nativescript-angular/router/page-router-outlet.ts
Fix https://github.com/NativeScript/nativescript-angular/issues/1735
=> fix(location-strategy): crash on going back with router-outlet after closing modal

CHANGELOG.md
=> chore: merge release into master

nativescript-angular/element-registry.ts
Package cannot be used with NativeScript 5.4.x
Package can be used with NativeScript 5.4.x
fixes: https://github.com/NativeScript/nativescript-angular/issues/1914
=> fix: add backwards compatibility for 'tns-core-modules' version 5.4.x

nativescript-angular/bin/update-app-ng-deps
fixes CI issues with path forming
=> fix: update-app-ng-deps

build/pack-scripts/pack-compat.ts, nativescript-angular-package/package.json
Work flow for jenkins job:
- npm i <prebuilt scooped package.tgz> --no-save
- npm run pack-with-scoped-version -- <version of prebuilt scooped package>  no-save-exact
=> chore: change script to pack compat package for release

CHANGELOG.md
=> release: cut the 8.20.4 release

nativescript-angular/router/ns-router-link-active.ts
=> fix(router): Link active directive: fix adding CSS class

nativescript-angular/common/detached-loader.ts
See #2257
Fixes missing function from #2257. Navigation should work properly again with ivy
Fixes #2256.
=> fix(detached-loader): detach loadWithFactory

nativescript-angular/platform-common.ts
=> fix: blank screen on hmr
